/** This file was automantically generated by auto_generate.py. DO NOT CHANGE IT!**/
#ifndef __AUTO_GENERATE_H
#define __AUTO_GENERATE_H

#include "cmodel.h"

#include "const.h"
#include "gain.h"
#include "limit.h"
#include "pid.h"
#include "switch.h"
#include "translate.h"

typedef struct _Prase_Datas_s {
	 const char* name;
	 CModel (*createCB)(uint32_t, uint32_t);
}Prase_Datas_s;

extern const Prase_Datas_s Prase_Datas[];
extern unsigned int Prase_Datas_len;

#endif
