/** This file was automantically generated by auto_generate.py. DO NOT CHANGE IT!**/
#include "auto_generate.h"

const Prase_Datas_s Prase_Datas[] = {
	{"CONST", const_create},
	{"GAIN", gain_create},
	{"LIMIT", limit_create},
	{"PID", pid_create},
	{"SWITCH", switch_create},
	{"TRANSLATE", translate_create},
};

unsigned int Prase_Datas_len = sizeof(Prase_Datas)/sizeof(Prase_Datas[0]);

